
# This file is automatically generated, you probably don't want to edit this

descriptivesOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descriptivesOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jmvplus",
                name="descriptives",
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

descriptivesResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descriptivesResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Descriptives")}))

descriptivesBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "descriptivesBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplus",
                name = "descriptives",
                version = c(1,0,0),
                options = options,
                results = descriptivesResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'full')
        }))

