
# This file is automatically generated, you probably don't want to edit this

scatOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jmvplus",
                name="scat",
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

scatResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Scatter Plot")}))

scatBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "scatBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplus",
                name = "scat",
                version = c(1,0,0),
                options = options,
                results = scatResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

