
# This file is automatically generated, you probably don't want to edit this

ttestisOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function( ...) {

            super$initialize(
                package="jmvplus",
                name="ttestis",
                requiresData=FALSE,
                ...)


        }),
    active = list(),
    private = list()
)

ttestisResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestisResults",
    inherit = jmvcore::Group,
    active = list(),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Independent Samples T-Test")}))

ttestisBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "ttestisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jmvplus",
                name = "ttestis",
                version = c(1,0,0),
                options = options,
                results = ttestisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'na')
        }))

